from enum import Enum


class TransactionStatus(str, Enum):
    PENDING_USER = "PENDING_USER"
    PENDING_FRAUD_CHECK = "PENDING_FRAUD_CHECK"
    PENDING_RECIPIENT = "PENDING_RECIPIENT"
    VALIDATED = "VALIDATED"
    REFUSED = "REFUSED"


class TransactionType(str, Enum):
    CLASSIC_VIREMENT = "CLASSIC_VIREMENT"
    SAFETRANSFER_VIREMENT = "SAFETRANSFER_VIREMENT"
    SAFETRANSFER_PRELEVEMENT = "SAFETRANSFER_PRELEVEMENT"
    CLASSIC_PRELEVEMENT = "CLASSIC_PRELEVEMENT"
    CB = "CB"
    CHEQUE = "CHEQUE"
