FROM python:3.11-slim

WORKDIR /app

# Copie des fichiers
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Lancement de Streamlit
CMD ["streamlit", "run", "Home.py", "--server.port=8501", "--server.address=0.0.0.0"]
