"""update transact entity

Revision ID: 7dedf3918658
Revises: 9925693c8747
Create Date: 2025-06-12 21:47:05.479279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dedf3918658'
down_revision: Union[str, None] = '9925693c8747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('safe_transaction_transaction_id', sa.Enum('CLASSIC_VIREMENT', 'SAFETRANSFER_VIREMENT', 'SAFETRANSFER_PRELEVEMENT', 'CLASSIC_PRELEVEMENT', 'CB', 'CHEQUE', name='transactiontype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'safe_transaction_transaction_id')
    # ### end Alembic commands ###
