"""init mig

Revision ID: 098d095864ab
Revises: 
Create Date: 2025-06-14 09:23:53.245889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098d095864ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_bank_user', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_bank_user'),
    sa.UniqueConstraint('mail')
    )
    op.create_table('interbank_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_source_id', sa.UUID(), nullable=False),
    sa.Column('user_dest_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_USER', 'PENDING_FRAUD_CHECK', 'PENDING_RECIPIENT', 'VALIDATED', 'REFUSED', name='transactionstatus'), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('double_auth_source', sa.Boolean(), nullable=True),
    sa.Column('double_auth_dest', sa.Boolean(), nullable=True),
    sa.Column('transaction_type', sa.Enum('TRANSFER', 'WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('source_code', sa.String(length=10), nullable=True),
    sa.Column('dest_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_dest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_source_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interbank_transactions')
    op.drop_table('users')
    # ### end Alembic commands ###
