"""transaction creation

Revision ID: 8aa4d35e5c76
Revises: c4dcd356afbf
Create Date: 2025-06-12 20:41:06.877435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa4d35e5c76'
down_revision: Union[str, None] = 'c4dcd356afbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interbank_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_source_id', sa.UUID(), nullable=False),
    sa.Column('user_dest_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_USER', 'PENDING_FRAUD_CHECK', 'PENDING_RECIPIENT', 'VALIDATED', 'REFUSED', name='transactionstatus'), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('double_auth_source', sa.Boolean(), nullable=True),
    sa.Column('double_auth_dest', sa.Boolean(), nullable=True),
    sa.Column('transaction_type', sa.Enum('CLASSIC_VIREMENT', 'SAFETRANSFER_VIREMENT', 'SAFETRANSFER_PRELEVEMENT', 'CLASSIC_PRELEVEMENT', 'CB', 'CHEQUE', name='transactiontype'), nullable=False),
    sa.Column('source_code', sa.String(length=10), nullable=True),
    sa.Column('dest_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_dest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_source_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interbank_transactions')
    # ### end Alembic commands ###
